{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ancientmc",
    "module": "acp-gradle",
    "version": "0.2.1.20250217.140504-BETA",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "acp-gradle-0.2.1.20250217.140504-BETA.jar",
          "url": "acp-gradle-0.2.1.20250217.140504-BETA.jar",
          "size": 50758,
          "sha512": "c891eb91098014490d2b429cb3c02756513ca8271a2d7a32855f0df35b1999d2ca5bb27ff9a01ca326bbf71ac76994720d446054893cc44cadd1ccee5993fefb",
          "sha256": "7b7dad497fb51533ddd3ea559285da0c1399fad48ac7a33734e09b2afdc07371",
          "sha1": "b3c4f57e1c9d79f515c4359db5a791935c8e2542",
          "md5": "dc79f7fa35aa9b104e34119c4467e70b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.18.0"
          }
        },
        {
          "group": "net.neoforged",
          "module": "srgutils",
          "version": {
            "requires": "1.0.9"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.27.1"
          }
        }
      ],
      "files": [
        {
          "name": "acp-gradle-0.2.1.20250217.140504-BETA.jar",
          "url": "acp-gradle-0.2.1.20250217.140504-BETA.jar",
          "size": 50758,
          "sha512": "c891eb91098014490d2b429cb3c02756513ca8271a2d7a32855f0df35b1999d2ca5bb27ff9a01ca326bbf71ac76994720d446054893cc44cadd1ccee5993fefb",
          "sha256": "7b7dad497fb51533ddd3ea559285da0c1399fad48ac7a33734e09b2afdc07371",
          "sha1": "b3c4f57e1c9d79f515c4359db5a791935c8e2542",
          "md5": "dc79f7fa35aa9b104e34119c4467e70b"
        }
      ]
    }
  ]
}
