{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ancientmc",
    "module": "commons",
    "version": "0.1.0-snapshot-3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "commons-0.1.0-snapshot-3.jar",
          "url": "commons-0.1.0-snapshot-3.jar",
          "size": 32159,
          "sha512": "83af322f4b16353dfa6f149d626166ee26b5cf15b4a414592a0f4a86c5f40a86b160970f6c364c3025182aefbee4a08ef7eaa3bf16888842b9efa264f0685093",
          "sha256": "cb5130b727da6be6cc9d6fec211260395bc60e2a05884be35ae9d520eafba787",
          "sha1": "633a3c39826608889cf914a6996f920c7fa13e58",
          "md5": "4ebd2764823d4bac15218b22530ad082"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.28.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.22.0"
          }
        },
        {
          "group": "com.mojang",
          "module": "datafixerupper",
          "version": {
            "requires": "9.0.19"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.6.0-jre"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "commons-0.1.0-snapshot-3.jar",
          "url": "commons-0.1.0-snapshot-3.jar",
          "size": 32159,
          "sha512": "83af322f4b16353dfa6f149d626166ee26b5cf15b4a414592a0f4a86c5f40a86b160970f6c364c3025182aefbee4a08ef7eaa3bf16888842b9efa264f0685093",
          "sha256": "cb5130b727da6be6cc9d6fec211260395bc60e2a05884be35ae9d520eafba787",
          "sha1": "633a3c39826608889cf914a6996f920c7fa13e58",
          "md5": "4ebd2764823d4bac15218b22530ad082"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "commons-0.1.0-snapshot-3-sources.jar",
          "url": "commons-0.1.0-snapshot-3-sources.jar",
          "size": 33051,
          "sha512": "872b0dcf2d693feb252b40880c22bc612c15d7bab6204b17cf8446299555b5e80ae2edc764b840272d1a49d58530ec9b2d002b10aceddb36921f1c7775d0e14d",
          "sha256": "f492346c1ea8dcaaebe918c4f9c761e45e085e8850379b93e2c723a9eea659ed",
          "sha1": "1389234dd449843767aa0cdafa837c4d8450715b",
          "md5": "7d19d4b5ddfb2d5cdfe1ee04203930fd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "commons-0.1.0-snapshot-3-javadoc.jar",
          "url": "commons-0.1.0-snapshot-3-javadoc.jar",
          "size": 158828,
          "sha512": "6a46cea54eb2d3db6f02e6fb57dbd82c61cd6e61ba82a5fdf9c9c7d2ebc9bdeec38fdcf59af44b53bd3863a82df2fbabdc358b124206d4517cebb4db56d36600",
          "sha256": "8d508f89bd49359607f1c26b6b5c6bdc41bbc528a14e9d76e96a8f1eaa599348",
          "sha1": "9f9f4bee9a167f0bdcdfc63df48e839ac9848096",
          "md5": "06e093afd5ec906938e7364894e08b9c"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "commons-0.1.0-snapshot-3-all.jar",
          "url": "commons-0.1.0-snapshot-3-all.jar",
          "size": 30355710,
          "sha512": "3cf529bae39cc3f7312869995a6d18c2b98a0a5fa51019d24af920ac37c85dcbaf03700aabd27520dc5ed978a9b655e6ad42561a48dbedaae10ffaff1f0d3491",
          "sha256": "28a13d83141947be09a58f694a4cc9880a03beefd2772d61e494035e1c17c9e6",
          "sha1": "d1f37f5db0df36c453e99c01dac18d65b4165771",
          "md5": "85e2ea0e611b3569c774f3ad2f8a211c"
        }
      ]
    }
  ]
}
