{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ancientmc",
    "module": "rosetta",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-0.1.3-base.jar",
          "url": "rosetta-0.1.3-base.jar",
          "size": 51257,
          "sha512": "8c5a65b8d9f72598db46c300b8c37dab58d24d8a3b49eec2ca4a8518cd9dd92e34fe1156e27896838680b630f333a6105a0415e494e7d35c26f7387b16b73093",
          "sha256": "5f42c32eb5e3d0b13b6e601ff1068cf11a16751d0c3564f0e4b9b9f376c0a231",
          "sha1": "e46870ae82ecf6db10b7645c47e4393c6d5af687",
          "md5": "93c9cde29349793185285b42802ff71c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "requires": "0.5.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-0.1.3-base.jar",
          "url": "rosetta-0.1.3-base.jar",
          "size": 51257,
          "sha512": "8c5a65b8d9f72598db46c300b8c37dab58d24d8a3b49eec2ca4a8518cd9dd92e34fe1156e27896838680b630f333a6105a0415e494e7d35c26f7387b16b73093",
          "sha256": "5f42c32eb5e3d0b13b6e601ff1068cf11a16751d0c3564f0e4b9b9f376c0a231",
          "sha1": "e46870ae82ecf6db10b7645c47e4393c6d5af687",
          "md5": "93c9cde29349793185285b42802ff71c"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-0.1.3-all.jar",
          "url": "rosetta-0.1.3-all.jar",
          "size": 608871,
          "sha512": "8640250bf16730a80f00822dd083a89dd297a22a6504b7ac09503d18f2c1987bb31ace8a410f4de11853e8be19923dfc8aa03166a003c6a96f7cc4f898eb5cda",
          "sha256": "0c4020ecbdc2b0b0bb7491b135e2262ec325b22d04180dfb98b41971c3901cd7",
          "sha1": "dae1090b04a65f18c672b30ae952ca57d8c10278",
          "md5": "4ce04815eab8475f75b17c3ae9de8894"
        }
      ]
    }
  ]
}
